In [89]:
#import dependencies
import requests
import pandas as pd

#Get Wake County Population
wake_county_pop_query_url = "https://api.opendatanetwork.com/data/v1/values?app_token=cQovpGcdUT1CSzgYk0KPYdAI0&describe=true&forecast=5&format=google&variable=demographics.population.count&entity_id=0500000US37183"
wake_county_pop_response = requests.get(wake_county_pop_query_url)
wake_county_pop_json = wake_county_pop_response.json()

In [90]:
# Create an empty data frame for Wake County Population
column_names = ("Year", "Population")
wakecountypop_df = pd.DataFrame(columns = column_names)
wakecountypop_df

Empty DataFrame
Columns: [Year, Population]
Index: []

In [88]:
wake_county_pop_year = []
wake_county_pop_count = []
for i in wake_county_pop_json["data"]["rows"]:

    wake_county_pop_year.append(i["c"][0]["v"])
    wake_county_pop_count.append(i["c"][1]["v"])
    
wakecountypop_df["Year"] = wake_county_pop_year
wakecountypop_df["Population"] = wake_county_pop_count
wakecountypop_df

    Year  Population
0   2009    828759.0
1   2010    850546.0
2   2011    879658.0
3   2012    905573.0
4   2013    929214.0
5   2014    952513.0
6   2015    976019.0
7   2016    998576.0
8   2017   1023811.0
9   2018   1048192.5
10  2019   1072574.0
11  2020   1096955.5
12  2021   1121337.0
13  2022   1145718.5